-- Search: model generations, embeddings, indexing job state, evaluation.
--
-- pgvector policy
-- ---------------
-- pgvector is optional. `CREATE EXTENSION vector` needs a superuser (or an
-- operator-installed extension) and the shared library on the server, so it is
-- attempted inside an exception block and every object that depends on it is
-- created conditionally. When the extension is absent the facilitator runs in
-- lexical-only mode: `catalog_embeddings` does not exist, no embedding job is
-- ever claimed, and `GET /discovery/search` serves PostgreSQL full-text results.
-- The checked-in Docker Compose file uses the `pgvector/pgvector` image, so the
-- default self-hosted path has it.

DO $$
BEGIN
  CREATE EXTENSION IF NOT EXISTS vector;
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'pgvector is unavailable (%); semantic search stays disabled and lexical search continues', SQLERRM;
END
$$;

-- One row per (provider, model, revision, dimension, pooling, normalization).
-- Exactly one generation may be active. Changing any of those fields creates a
-- new generation and requires an explicit reindex; embeddings from different
-- generations are never compared.
CREATE TABLE IF NOT EXISTS search_model_generations (
  -- integer so it fits `catalog_index_jobs.generation`, which is the existing
  -- job queue's generation column.
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider text NOT NULL,
  model_id text NOT NULL,
  model_revision text NOT NULL,
  dimension integer NOT NULL CHECK (dimension BETWEEN 1 AND 16000),
  pooling text NOT NULL CHECK (pooling IN ('cls', 'mean')),
  normalization text NOT NULL CHECK (normalization IN ('l2', 'none')),
  checksum text,
  status text NOT NULL DEFAULT 'building'
    CHECK (status IN ('building', 'active', 'retired', 'failed')),
  documents_indexed bigint NOT NULL DEFAULT 0,
  last_error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  activated_at timestamptz,
  retired_at timestamptz,
  UNIQUE (provider, model_id, model_revision, dimension, pooling, normalization)
);

CREATE UNIQUE INDEX IF NOT EXISTS search_one_active_generation
  ON search_model_generations((status)) WHERE status = 'active';

-- Dense vectors live in one table per generation, `catalog_embeddings_g<id>`,
-- created by `search_create_generation_storage` when the generation is
-- activated.
--
-- A single shared table cannot work: pgvector evaluates an index expression
-- independently of a partial index predicate, so an existing
-- `((embedding::vector(64)))` index rejects a 1024-dimension insert even for a
-- different generation. Separate typed tables make mixing dimensions
-- structurally impossible rather than merely forbidden, and let each generation
-- carry a plain HNSW index on a `vector(d)` column with no cast at query time.

-- Extend the existing job queue rather than introducing a second one.
ALTER TABLE catalog_index_jobs DROP CONSTRAINT IF EXISTS catalog_index_jobs_state_check;
ALTER TABLE catalog_index_jobs ADD CONSTRAINT catalog_index_jobs_state_check
  CHECK (state IN ('pending', 'leased', 'done', 'failed', 'dead'));

ALTER TABLE catalog_index_jobs ADD COLUMN IF NOT EXISTS first_failed_at timestamptz;
ALTER TABLE catalog_index_jobs ADD COLUMN IF NOT EXISTS dead_reason text;
ALTER TABLE catalog_index_jobs ADD COLUMN IF NOT EXISTS completed_at timestamptz;

CREATE INDEX IF NOT EXISTS catalog_jobs_generation_idx
  ON catalog_index_jobs(kind, generation, state, next_run_at);

-- The compiler version lets a formatter change invalidate documents without
-- touching the catalog declaration itself.
ALTER TABLE catalog_search_documents ADD COLUMN IF NOT EXISTS compiler_version integer NOT NULL DEFAULT 1;

-- Ranking provenance: what was shown, for which query, under which model.
CREATE TABLE IF NOT EXISTS search_impressions (
  id bigserial PRIMARY KEY,
  session_id uuid NOT NULL,
  query_hash text NOT NULL,
  query_text text,
  mode text NOT NULL CHECK (mode IN ('lexical', 'semantic', 'hybrid')),
  reranked boolean NOT NULL DEFAULT false,
  generation_id integer REFERENCES search_model_generations(id),
  ranking_config jsonb NOT NULL DEFAULT '{}'::jsonb,
  resource_id bigint NOT NULL REFERENCES catalog_resources(id),
  version_id bigint NOT NULL REFERENCES catalog_resource_versions(id),
  position integer NOT NULL,
  score double precision NOT NULL,
  degraded jsonb NOT NULL DEFAULT '{}'::jsonb,
  latency_ms integer,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS search_impressions_resource_idx
  ON search_impressions(resource_id, created_at DESC);
CREATE INDEX IF NOT EXISTS search_impressions_time_idx ON search_impressions(created_at DESC);
CREATE INDEX IF NOT EXISTS search_impressions_session_idx ON search_impressions(session_id);

-- Versioned golden set. Judgments are keyed on `resource_key` so a fixture
-- survives reindexing and database resets.
CREATE TABLE IF NOT EXISTS search_eval_suites (
  id bigserial PRIMARY KEY,
  name text NOT NULL UNIQUE,
  description text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS search_eval_queries (
  id bigserial PRIMARY KEY,
  suite_id bigint NOT NULL REFERENCES search_eval_suites(id) ON DELETE CASCADE,
  query text NOT NULL,
  query_class text NOT NULL DEFAULT 'general',
  filters jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes text,
  UNIQUE (suite_id, query)
);

CREATE TABLE IF NOT EXISTS search_eval_judgments (
  id bigserial PRIMARY KEY,
  query_id bigint NOT NULL REFERENCES search_eval_queries(id) ON DELETE CASCADE,
  resource_key text NOT NULL,
  -- 0 = must not rank, 1 = marginal, 2 = relevant, 3 = ideal.
  grade integer NOT NULL CHECK (grade BETWEEN 0 AND 3),
  rationale text,
  UNIQUE (query_id, resource_key)
);

CREATE TABLE IF NOT EXISTS search_eval_runs (
  id bigserial PRIMARY KEY,
  suite_id bigint NOT NULL REFERENCES search_eval_suites(id) ON DELETE CASCADE,
  mode text NOT NULL,
  reranked boolean NOT NULL DEFAULT false,
  generation_id integer REFERENCES search_model_generations(id),
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
  catalog_size integer NOT NULL DEFAULT 0,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz
);

CREATE TABLE IF NOT EXISTS search_eval_run_results (
  id bigserial PRIMARY KEY,
  run_id bigint NOT NULL REFERENCES search_eval_runs(id) ON DELETE CASCADE,
  query_id bigint NOT NULL REFERENCES search_eval_queries(id) ON DELETE CASCADE,
  returned jsonb NOT NULL DEFAULT '[]'::jsonb,
  metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
  degraded jsonb NOT NULL DEFAULT '{}'::jsonb,
  latency_ms integer NOT NULL DEFAULT 0,
  UNIQUE (run_id, query_id)
);


/**
 * Turns free text into an OR tsquery.
 *
 * `websearch_to_tsquery` ANDs every term, which under the `simple`
 * configuration also means every stopword: "current weather for a city" would
 * require the document to contain "for" and "a". Recall is the primary gate for
 * an agent choosing from the first few results, so the query is split into word
 * tokens and ORed, and `ts_rank_cd` orders by how many terms actually matched.
 * The split keeps only `[a-z0-9]` runs, so no tsquery operator can be injected.
 */
CREATE OR REPLACE FUNCTION search_or_tsquery(configuration regconfig, raw text)
RETURNS tsquery LANGUAGE sql IMMUTABLE AS $$
  SELECT COALESCE(
    to_tsquery(
      configuration,
      NULLIF(
        array_to_string(
          ARRAY(
            SELECT quote_literal(token)
            FROM unnest(regexp_split_to_array(lower(raw), '[^a-z0-9]+')) AS token
            WHERE length(token) > 0
          ),
          ' | '
        ),
        ''
      )
    ),
    to_tsquery(configuration, 'x402zzzznomatch')
  );
$$;

/**
 * Creates the storage and HNSW index for one generation, and returns its table
 * name. Idempotent, and a no-op without pgvector.
 */
CREATE OR REPLACE FUNCTION search_create_generation_storage(target integer) RETURNS text
LANGUAGE plpgsql AS $fn$
DECLARE
  target_dimension integer;
  storage_name text;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'vector') THEN
    RETURN NULL;
  END IF;
  SELECT dimension INTO target_dimension FROM search_model_generations WHERE id = target;
  IF target_dimension IS NULL THEN
    RAISE EXCEPTION 'unknown search model generation %', target;
  END IF;
  storage_name := format('catalog_embeddings_g%s', target);
  IF EXISTS (SELECT 1 FROM pg_class WHERE relname = storage_name) THEN
    RETURN storage_name;
  END IF;
  EXECUTE format($ddl$
    CREATE TABLE %I (
      id bigserial PRIMARY KEY,
      generation_id integer NOT NULL REFERENCES search_model_generations(id) ON DELETE CASCADE,
      version_id bigint NOT NULL REFERENCES catalog_resource_versions(id) ON DELETE CASCADE,
      resource_id bigint NOT NULL REFERENCES catalog_resources(id),
      embedding_model_id text NOT NULL,
      embedding_model_version text NOT NULL,
      embedding_dimension integer NOT NULL CHECK (embedding_dimension = %s),
      embedding vector(%s) NOT NULL,
      source_hash text NOT NULL,
      created_version bigint NOT NULL,
      status text NOT NULL DEFAULT 'ready' CHECK (status IN ('ready', 'stale')),
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now(),
      UNIQUE (version_id)
    )$ddl$, storage_name, target_dimension, target_dimension);
  EXECUTE format('CREATE INDEX %I ON %I USING hnsw (embedding vector_cosine_ops)',
                 storage_name || '_hnsw', storage_name);
  EXECUTE format('CREATE INDEX %I ON %I(resource_id)', storage_name || '_resource', storage_name);
  EXECUTE format('CREATE INDEX %I ON %I(created_version, status)',
                 storage_name || '_snapshot', storage_name);
  RETURN storage_name;
END;
$fn$;

/** Drops a retired generation's storage once its rollback window has passed. */
CREATE OR REPLACE FUNCTION search_drop_generation_storage(target integer) RETURNS void
LANGUAGE plpgsql AS $fn$
BEGIN
  EXECUTE format('DROP TABLE IF EXISTS %I', format('catalog_embeddings_g%s', target));
END;
$fn$;
