import type { Metadata } from "next";

import { LegalDocument, LegalShell } from "@/components/legal-shell";

export const metadata: Metadata = {
  title: "Privacy Policy — openx402",
  description: "What openx402 collects, what it does not collect, and how to opt out.",
};

export default function Page() {
  return (
    <LegalShell>
      <LegalDocument title="Privacy Policy" updated="14 August 2026">
        <section>
          <h2>Who we are</h2>
          <p>
            openx402 is a public, read-only explorer for the x402 payment protocol on the Stellar network, operated by
            Ithaca Labs. Its source code is published under the Apache License 2.0 at{" "}
            <a href="https://github.com/Ithaca-Labs/openx402" rel="noreferrer noopener" target="_blank">github.com/Ithaca-Labs/openx402</a>,
            so the behaviour described below can be verified directly against the code.
          </p>
          <p>
            This policy covers the openx402 website. It does not cover the independent services listed in our catalog,
            the Stellar network itself, or any other site we link to.
          </p>
        </section>

        <section>
          <h2>What we collect</h2>
          <p>
            We record anonymous, route-level usage events so we can see which parts of the explorer get used. Each event
            stores exactly five things:
          </p>
          <ul>
            <li>the event type — either <code>page_view</code> or <code>impression</code></li>
            <li>the path you visited, for example <code>/discover</code></li>
            <li>an element key identifying the section that came into view, where applicable</li>
            <li>a timestamp</li>
            <li>a <strong>SHA-256 hash</strong> of a random identifier generated by your browser</li>
          </ul>
          <p>
            That random identifier is created locally by your browser and is not derived from anything about you or your
            device. It is sent to our server, which hashes it before writing it to storage — <strong>the raw value is
            never saved</strong>. The hash lets us count returning visitors approximately without being able to identify
            anyone.
          </p>
          <p>
            These events are only recorded on the explorer pages. The landing page does not run any analytics at all.
          </p>
        </section>

        <section>
          <h2>What we do not collect</h2>
          <p>
            We do not record or store your IP address, user agent, referring page, or location. We do not use cookies,
            advertising trackers, session replay, fingerprinting, or any cross-site tracking. There are no user accounts
            and no sign-up, so we hold no names, email addresses, or passwords.
          </p>
          <p>
            openx402 never connects a wallet, never asks you to sign anything, and never takes custody of funds or keys.
            We therefore hold no wallet addresses, balances, or payment details of yours. We do not sell or share data
            with anyone, because we do not have anything to sell or share.
          </p>
        </section>

        <section>
          <h2>Browser storage</h2>
          <p>
            openx402 sets no cookies. It uses two entries in your browser&rsquo;s local storage, both readable and
            clearable by you at any time:
          </p>
          <ul>
            <li><code>openx402-site-visitor</code> — the random analytics identifier described above</li>
            <li><code>openx402-theme</code> — whether you chose the light or dark theme</li>
          </ul>
          <p>Neither is transmitted to any third party.</p>
        </section>

        <section>
          <h2>Third parties</h2>
          <p>
            Some images on the site are loaded from other domains. Requesting an image reveals your IP address and
            standard request headers to the host serving it, which is an ordinary consequence of loading a web page and
            is not something we control or receive. The hosts involved are:
          </p>
          <ul>
            <li><a href="https://www.dicebear.com" rel="noreferrer noopener" target="_blank">api.dicebear.com</a> — generates the placeholder identicons shown next to catalog listings</li>
            <li>initia.xyz — serves decorative artwork on the landing page</li>
          </ul>
          <p>
            The site also links out to documentation, Stellar, block explorers, and social accounts. Once you follow an
            outbound link, that destination&rsquo;s own privacy policy applies.
          </p>
          <p>
            Our hosting provider may keep its own server request logs, as any web host does. Those logs are outside the
            scope of this policy and are not used by us for analytics.
          </p>
        </section>

        <section>
          <h2>Aggregate statistics are public</h2>
          <p>
            The usage figures produced from these events are published openly on our analytics page and its underlying
            API endpoint, neither of which requires a login. Only aggregate numbers are exposed — visitor counts, counts
            per day, and the most-visited paths. Individual events and hashed identifiers are never shown.
          </p>
        </section>

        <section>
          <h2>Retention</h2>
          <p>
            We do not currently operate an automatic deletion schedule, so analytics events may be retained
            indefinitely. Because the stored records contain no identifiers we can link back to a person, we cannot
            locate or delete the events associated with a particular individual on request.
          </p>
        </section>

        <section>
          <h2>Your choices</h2>
          <p>
            You can clear or block local storage for this site, which removes the random identifier and causes a new one
            to be generated on your next visit. You can block requests to our analytics endpoint, or browse with
            JavaScript disabled. None of these degrade the site&rsquo;s content — analytics failures are ignored
            silently by design.
          </p>
        </section>

        <section>
          <h2>Children</h2>
          <p>
            openx402 is developer tooling and is not directed at children under 13. We do not knowingly collect
            information from them.
          </p>
        </section>

        <section>
          <h2>Changes</h2>
          <p>
            We may update this policy as the site changes. The revision date at the top of this page always reflects the
            current version, and the full history is visible in our public repository.
          </p>
        </section>

        <section>
          <h2>Contact</h2>
          <p>
            Questions about this policy can go to <a href="mailto:labsithaca@gmail.com">labsithaca@gmail.com</a>.
            Security issues are best reported privately through the GitHub security advisory flow on our repository.
          </p>
        </section>
      </LegalDocument>
    </LegalShell>
  );
}
